---
#- name: Copy web JS config to scripts dir
  #template: src=web-config-js.j2 dest="{{ web_scripts_dir}}/config.js"
  #sudo: no

- name: Build production web app
  command: >
    /usr/bin/docker run
      --name driver-web
      --log-driver syslog
      driver/web:latest
      build

#- name: Copy editor JS config to scripts dir
  #template: src=editor-config-js.j2 dest="{{ editor_scripts_dir}}/config.js"
  #sudo: no

- name: Build production editor app
  command: >
    /usr/bin/docker run
      --name driver-editor
      --log-driver syslog
      driver/editor:latest
      build
