---
driver_user: "{{ ansible_ssh_user }}"
driver_conf:
  DRIVER_DB_NAME: "{{ postgresql_database }}"
  DRIVER_DB_USER: "{{ postgresql_username }}"
  DRIVER_DB_PASSWORD: "{{ postgresql_password }}"
  DRIVER_DB_HOST: "{{ postgresql_host }}"
  DRIVER_DB_PORT: "{{ postgresql_port }}"
  DJANGO_STATIC_ROOT: "{{ root_static_dir }}"
  DJANGO_MEDIA_ROOT: "{{ root_media_dir }}"
  DJANGO_POSTGIS_VERSION: "{{ driver_postgis_version }}"
  DJANGO_SECRET_KEY: "{{ driver_secret_key }}"
driver_secret_key: "{{ postgresql_password | md5 }}"
driver_postgis_version: 2.1.3

root_app_dir: "/opt/app"
root_www_dir: "/var/www"
root_static_dir: "{{ root_www_dir }}/static"
root_media_dir: "{{ root_www_dir }}/media"

database_host: "database.service.driver.internal"
