# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-07 20:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_auto_20160527_2236'),
    ]

    operations = [
        migrations.RunSQL([
            'GRANT SELECT ON auth_user TO windshaft',
            'GRANT SELECT ON data_recordauditlogentry TO windshaft'
        ])
    ]
