# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-10 18:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grout', '0024_auto_20180716_1605'),
        ('data', '0011_copy_ashlar_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverRecord',
            fields=[
                ('record_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='grout.Record')),
                ('weather', models.CharField(blank=True, max_length=50, null=True)),
                ('light', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('city_district', models.CharField(blank=True, max_length=50, null=True)),
                ('county', models.CharField(blank=True, max_length=50, null=True)),
                ('neighborhood', models.CharField(blank=True, max_length=50, null=True)),
                ('road', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('grout.record',),
        ),
        migrations.AlterField(
            model_name='recordauditlogentry',
            name='record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to='grout.Record'),
        ),
        migrations.AddField(
            model_name='recordauditlogentry',
            name='driver_record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.DriverRecord'),
        ),
        migrations.AddField(
            model_name='recordduplicate',
            name='driver_duplicate_record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_duplicate_record', to='data.DriverRecord'),
        ),
        migrations.AddField(
            model_name='recordduplicate',
            name='driver_record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_record', to='data.DriverRecord'),
        ),
    ]
