# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-11 17:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_copy_grout_data'),
    ]

    # We want to replace our existing `record` fields, which are Foreign Keys to grout.Record, with
    # identically named fields that are Foreign Keys to `data.DriverRecord` instead. We've copied
    # over the data between these two fields in previous migrations, so now we can drop the old
    # references to grout.Record and swap in the `driver_record` fields, which reference
    # DriverRecord. DriverRecord is a subclasso of grout.Record. We do this in one migration so that
    # there's no chance of accidentally leaving the app in a state where the field names it expects
    # are missing.
    operations = [
        migrations.RemoveField(
            model_name='recordduplicate',
            name='duplicate_record',
        ),
        migrations.RenameField(
            model_name='recordduplicate',
            old_name='driver_duplicate_record',
            new_name='duplicate_record',
        ),

        migrations.RemoveField(
            model_name='recordduplicate',
            name='record',
        ),
        migrations.RenameField(
            model_name='recordduplicate',
            old_name='driver_record',
            new_name='record',
        ),

        migrations.RemoveField(
            model_name='recordauditlogentry',
            name='record',
        ),
        migrations.RenameField(
            model_name='recordauditlogentry',
            old_name='driver_record',
            new_name='record',
        )
    ]
