/**
 * Responsible for creating the jsonschemas necessary to create the edit form
 * for a recordtype schema definition
 *
 * In order to add a new FieldType, you need to do the following:
 * 1. Add a key/value pair to the module.FieldTypes object
 * 2. Add a new method in the module.Fields object for instantiating new schema objects
 *    for this type. Ensure your newly created object has a key 'options' which is of the form:
 *    {
 *        fieldType: '<new fieldtype key>'
 *    }
 *    This is so that when we serialize this object to data and back, we can remember what
 *    type of field it is.
 * 3. Add a new case for this new FieldType in the fieldFromKey method
 *
 * @return {[type]} [description]
 */
(function () {
    'use strict';

    /* ngInject */
    function Schemas() {
        var module = {
            JsonObject: jsonObject,
            FieldTypes: {
                'text': {
                    label: 'Text Field',
                    jsonType: 'string',
                    create: textField
                },
                'selectlist': {
                    label: 'Select List',
                    jsonType: 'string',
                    create: selectList,
                },
                'image': {
                    label: 'Image Uploader',
                    jsonType: 'string',
                    create: imageUploader
                }
            },
            Fields: {
                TextField: textField,
                SelectList: selectList,
                ImageUploader: imageUploader
            },
            addVersion4Declaration: addVersion4Declaration,
            fieldFromKey: fieldFromKey,
            definitionFromSchemaFormData: definitionFromSchemaFormData,
            encodeJSONPointer: encodeJSONPointer
        };
        return module;

        /**
         * Map one of the field keys in Schemas.FieldTypes to one of the fields
         * in Schemas.Fields
         * @param  {string} fieldKey
         * @param  {object} fieldOptions Passed directly to Fields constructors
         * @return {object} jsonschema object generated by field method
         */
        function fieldFromKey(fieldKey, fieldOptions) {
            fieldOptions = fieldOptions || {};
            if (module.FieldTypes[fieldKey] === undefined) {
                throw 'key must be one of Schemas.FieldTypes';
            }
            return module.FieldTypes[fieldKey].create(fieldOptions);
        }

        /**
         * Encode a string so that it complies with the JSON Pointer spec
         * http://tools.ietf.org/html/draft-pbryan-zyp-json-pointer-02
         * This is what is used in $ref to specify sub-schema paths
         * @param {string} str
         * @return {string} Currently just returns encodeURIComponent(string)
         */
        function encodeJSONPointer(str) {
            // TODO: Technically, we should be doing this:
            // return encodeURIComponent(str);
            // But json-editor doesn't seem to support that properly.
            return str;
        }

        /**
         * Converts part of the output of a Schema Entry Form (data about fields)
         * into a snippet designed to be inserted into the 'properties' key of a Data Form Schema
         * which would be used for data entry / editing. Does not perform validation.
         * @param {object} fieldData The value of one Schema Entry Form field, specifying required,
         *      searchable, possible values, etc.
         * @return {object} A snippet designed to be inserted into the 'properties' of a Data Form
         *      Schema
         */
        // TODO: This monolithic function isn't great; investigate more modular options
        function _propertyFromSchemaFieldData(fieldData) {
            var propertyDefinition = {};
            propertyDefinition.type = module.FieldTypes[fieldData.fieldType].jsonType;

            if (fieldData.fieldType === 'selectlist') {
                propertyDefinition.enum = fieldData.fieldOptions;
            }
            if (fieldData.fieldType === 'image') {
                propertyDefinition.media = {
                    binaryEncoding: 'base64',
                    type: 'image/jpeg'
                };
            }
            return propertyDefinition;
        }

        /**
         * Converts the outut of a Schema Entry Form into a sub-schema designed to be
         * inserted into the 'definitions' key of a Data Form Schema. Does not perform
         * validation.
         * @param {array} formData The values in the Schema Form, defining the fields in
         *      this Data Form Schema
         */
        function definitionFromSchemaFormData(formData) {
            var definition = {
                type: 'object',
                properties: {}
            };

            // properties
            _.each(formData, function(fieldData) {
                definition.properties[fieldData.fieldTitle] = _propertyFromSchemaFieldData(fieldData);
            });

            // required
            // A list containing the titles of properties which are required.
            definition.required = _.pluck(_.filter(formData, function(fieldData) {
                    return fieldData.isRequired;
                }), 'fieldTitle');
            return definition;
        }

        /**
         * Adds a $schema keyword to an object; this declares that the object is JSON-Schema v4
         * @param {object} schema Object to which the declaration should be added
         * @return {object} The schema with the $schema keyword added, pointing to Draft 4
         */
        function addVersion4Declaration(schema) {
            return angular.extend(schema, { $schema: 'http://json-schema.org/draft-04/schema#' });
        }

        function jsonObject(newObject) {
            newObject = newObject || {};
            return angular.extend({}, {
                /* jshint camelcase: false */
                type: 'object',
                title: '',
                plural_title: '',
                description: '',
                properties: {},
                definitions: {}
                /* jshint camelcase: true */
            }, newObject);
        }

        function textField(newField) {
            newField = newField || {};
            var newTextField = jsonObject(newField);
            newTextField = angular.extend(newTextField, {
                headerTemplate: '{{ self.fieldTitle }}',
                properties: {
                    fieldTitle: {
                        type: 'string',
                        title: 'Field Title'
                    },
                    isRequired: {
                        type: 'boolean',
                        format: 'checkbox',
                        title: 'Required'
                    },
                    isSearchable: {
                        type: 'boolean',
                        format: 'checkbox',
                        title: 'Filterable/Searchable'
                    },
                    textOptions: {
                        type: 'string',
                        title: 'Text Options',
                        enum: [
                            'text',
                            'textarea',
                            'number',
                            'color',
                            'tel',
                            'datetime',
                            'url'
                        ],
                        options: {
                            /* jshint camelcase: false */
                            enum_titles: [
                                'Single line text',
                                'Paragraph text',
                                'Number',
                                'HTML Color',
                                'Telephone number',
                                'Date / Time',
                                'Website URL'
                            ]
                            /* jshint camelcase: true */
                        }
                    },
                    fieldType: {
                        options: {
                            hidden: true
                        },
                        type: 'string'
                        // Set default: 'text' below since default is a reserved word
                    }
                },
                required: ['fieldTitle']
            });
            newTextField.properties.fieldType['default'] = 'text';
            return newTextField;

        }

        function selectList(newList) {
            newList = newList || {};
            var newSelectList = jsonObject(newList);
            newSelectList = angular.extend(newSelectList, {
                headerTemplate: '{{ self.fieldTitle }}',
                properties: {
                    fieldTitle: {
                        type: 'string',
                        title: 'Field Title'
                    },
                    isRequired: {
                        type: 'boolean',
                        format: 'checkbox',
                        title: 'Required'
                    },
                    isSearchable: {
                        type: 'boolean',
                        format: 'checkbox',
                        title: 'Filterable/Searchable'
                    },
                    displayType: {
                        type: 'string',
                        enum: [
                            'select',
                            'checkbox'
                        ]
                    },
                    fieldOptions: {
                        title: 'Field Options',
                        type: 'array',
                        format: 'table',
                        uniqueItems: true,
                        items: {
                            type: 'string',
                            title: 'Option value'
                        }
                    },
                    fieldType: {
                        options: {
                            hidden: true
                        },
                        type: 'string'
                        // Set default: 'selectlist' below since default is a reserved word
                    }
                },
                required: ['fieldTitle']
            });
            newSelectList.properties.fieldType['default'] = 'selectlist';
            return newSelectList;
        }

        function imageUploader(newImage) {
            newImage = newImage || {};
            var newImageUploader = jsonObject(newImage);
            newImageUploader = angular.extend(newImageUploader, {
                headerTemplate: '{{ self.fieldTitle }}',
                properties: {
                    fieldTitle: {
                        type: 'string',
                        title: 'Field Title',
                    },
                    isRequired: {
                        type: 'boolean',
                        format: 'checkbox',
                        title: 'Required'
                    },
                    fieldType: {
                        options: {
                            hidden: true
                        },
                        type: 'string'
                        // Set default: 'image' below since default is a reserved word
                    }
                },
                required: ['fieldTitle']
            });
            newImageUploader.properties.fieldType['default'] = 'image';
            return newImageUploader;
        }
    }

    angular.module('ase.schemas')
    .service('Schemas', Schemas);

})();
