FROM quay.io/azavea/django:0.1.1

RUN mkdir -p /opt/app
WORKDIR /opt/app

COPY . /opt/app

# install dependencies for django-oidc
RUN apt-get update && apt-get install -y \
    libffi-dev \
    python-dev

RUN pip install --no-cache-dir --process-dependency-links --allow-external djsonb -r requirements.txt

EXPOSE 4000

CMD ["driver.wsgi", "-w3", "-b:4000", "-kgevent"]
