#!/usr/bin/env bash

#########################################
# Set up DRIVER for deployment.
# Requires python3.6 with pip installed.
#########################################

echo 'Setting up virtual environment...'

# Remove virtual environment if it already exists
rm -rf env

# Make sure virtualenv is installed
pip install virtualenv

# Create new python3.6 virtual environment
virtualenv -p python3.6 env

echo 'Installing Python dependencies in virtual environment...'

# Install dependencies within virtual environment
env/bin/pip install jinja2 click

echo 'Running script...'

# Run Python script
env/bin/python scripts/generate_deployment_config.py
