---
- name: Create Nginx configuration directory
  file: path=/etc/nginx/conf.d
        recurse=yes
        state=directory

- name: Configure Nginx service definition
  template: src=nginx.conf.j2 dest=/etc/init/nginx.conf
  notify:
    - Restart Nginx
